openapi: 3.0.0
info:
  title: Your API Title
  description: Your API Description
  version: 1.0.0
paths:
  /signup:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
                  enum: [VISITOR, WRITER, ADMIN]
      responses:
        '200':
          description: User created successfully
        '400':
          description: Bad request
